# -*- coding: utf-8 -*-
"""Dataframe

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VE1GPFblTX_cIftEaf-fFb73tgougbMz
"""

!pip install pyspark

import pandas as pd
pd.read_csv('/content/fixed_year_2020_quarter_01.csv')

from pyspark.sql import SparkSession

from pyspark.sql.functions import col

spark = SparkSession.builder.appName('Dataframe').getOrCreate()

dataframe_csv = spark.read.option('header', 'true').csv('/content/fixed_year_2020_quarter_01.csv')
dataframe_csv.select("Name", "Rank Upload").show()

dataframe_csv = spark.read.option('header', 'true').csv('/content/fixed_year_2020_quarter_01.csv')
dataframe_csv.select(dataframe_csv.columns[0],dataframe_csv.columns[1],dataframe_csv.columns[2]).show(20)

dataframe_csv = spark.read.option('header', 'true').csv('/content/fixed_year_2020_quarter_01.csv')
dataframe_csv.orderBy((col("Number of Records")).asc()).show(truncate=False)

dataframe_csv.filter(dataframe_csv.Devices < 100).show()

dataframe_csv.filter(col("Rank Download") == 1).show()

dataframe_csv.filter(col("Rank Download") == 234).show()

dataframe_csv.filter(col("Name") == 'Philippines').show()